{% set base_name = "libignition-cmake" %}
{% set version = "2.1.1" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://bitbucket.org/ignitionrobotics/ign-cmake/get/ignition-cmake{{ major_version }}_{{ version }}.tar.gz
    sha256: 32e9c96930375bd3c2681269ae6a2d2364cd9013a14e510410780ea0cc92763d
    patches:
      - examples.patch  # [linux]
      - FindGTS.cmake.patch  # [win]
      - FindIgnOGRE.cmake.patch  # [win]

build:
  number: 2
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkgconfig  # [not win]

test:
  commands:
    - test -f ${PREFIX}/share/cmake/ignition-cmake{{ major_version }}/ignition-cmake{{ major_version }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\share\\cmake\\ignition-cmake{{ major_version }}\\ignition-cmake{{ major_version }}-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/ignitionrobotics/ign-cmake
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Ignition CMake : CMake Modules for Ignition Projects'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
