{% set base_name = "libignition-cmake" %}
{% set version = "2.15.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-cmake/archive/ignition-cmake{{ major_version }}_{{ version }}.tar.gz
    sha256: e89e72bbf9d3ba27442db76478f68a1e56cf280b33c79cdcf23d7a13ea35980d
    patches:
      - 315.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkgconfig  # [not win]

test:
  commands:
    - test -f ${PREFIX}/share/cmake/ignition-cmake{{ major_version }}/ignition-cmake{{ major_version }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\share\\cmake\\ignition-cmake{{ major_version }}\\ignition-cmake{{ major_version }}-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-cmake
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Ignition CMake : CMake Modules for Ignition Projects'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
